sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abdulmansour/docker-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true abdulmansour/docker-aws npm run test